export const TOP_STORIES_REQUEST = 'TOP_STORIES_REQUEST';
export const TOP_STORIES_SUCCESS = 'TOP_STORIES_SUCCESS';
export const TOP_STORIES_ERROR = 'TOP_STORIES_ERROR';

export const ARTICLE_REQUEST = 'ARTICLE_REQUEST';
export const ARTICLE_RESPONSE = 'ARTICLE_RESPONSE';
export const ARTICLE_ERROR = 'ARTICLE_ERROR';